[2022-11-02T16:35:47.062-0300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: get_urls_googleshopping.search_products manual__2022-11-02T19:35:43.144368+00:00 [queued]>
[2022-11-02T16:35:47.071-0300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: get_urls_googleshopping.search_products manual__2022-11-02T19:35:43.144368+00:00 [queued]>
[2022-11-02T16:35:47.072-0300] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-02T16:35:47.072-0300] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-02T16:35:47.072-0300] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-02T16:35:47.082-0300] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): search_products> on 2022-11-02 19:35:43.144368+00:00
[2022-11-02T16:35:47.088-0300] {standard_task_runner.py:55} INFO - Started process 34889 to run task
[2022-11-02T16:35:47.099-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'get_urls_googleshopping', 'search_products', 'manual__2022-11-02T19:35:43.144368+00:00', '--job-id', '378', '--raw', '--subdir', 'DAGS_FOLDER/ETL_google_urls_sellers.py', '--cfg-path', '/tmp/tmpus990dvm']
[2022-11-02T16:35:47.099-0300] {standard_task_runner.py:83} INFO - Job 378: Subtask search_products
[2022-11-02T16:35:47.250-0300] {task_command.py:376} INFO - Running <TaskInstance: get_urls_googleshopping.search_products manual__2022-11-02T19:35:43.144368+00:00 [running]> on host debian
[2022-11-02T16:35:47.557-0300] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_urls_googleshopping
AIRFLOW_CTX_TASK_ID=search_products
AIRFLOW_CTX_EXECUTION_DATE=2022-11-02T19:35:43.144368+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-02T19:35:43.144368+00:00
[2022-11-02T16:35:47.609-0300] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/pandas/compat/_optional.py", line 141, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/debian/etlhausz/airflow/dags/ETL_google_urls_sellers.py", line 50, in search_products
    data = pd.read_excel(r"/home/debian/etlhausz/excelfiles/google.xlsx")
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 482, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/pandas/io/excel/_base.py", line 1695, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/pandas/io/excel/_openpyxl.py", line 556, in __init__
    import_optional_dependency("openpyxl")
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/pandas/compat/_optional.py", line 144, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
[2022-11-02T16:35:47.654-0300] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=get_urls_googleshopping, task_id=search_products, execution_date=20221102T193543, start_date=20221102T193547, end_date=20221102T193547
[2022-11-02T16:35:47.712-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 378 for task search_products (Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.; 34889)
[2022-11-02T16:35:47.747-0300] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-02T16:35:47.931-0300] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
