[2022-11-06T15:59:30.282-0300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: get_all_nfe_supply.get_endpoint_all_notas scheduled__2022-11-05T00:00:00+00:00 [queued]>
[2022-11-06T15:59:30.299-0300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: get_all_nfe_supply.get_endpoint_all_notas scheduled__2022-11-05T00:00:00+00:00 [queued]>
[2022-11-06T15:59:30.299-0300] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-06T15:59:30.299-0300] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-06T15:59:30.299-0300] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-06T15:59:30.318-0300] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): get_endpoint_all_notas> on 2022-11-05 00:00:00+00:00
[2022-11-06T15:59:30.323-0300] {standard_task_runner.py:55} INFO - Started process 2765 to run task
[2022-11-06T15:59:30.382-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'get_all_nfe_supply', 'get_endpoint_all_notas', 'scheduled__2022-11-05T00:00:00+00:00', '--job-id', '385', '--raw', '--subdir', 'DAGS_FOLDER/get_endpoint.py', '--cfg-path', '/tmp/tmpuwhi48q_']
[2022-11-06T15:59:30.409-0300] {standard_task_runner.py:83} INFO - Job 385: Subtask get_endpoint_all_notas
[2022-11-06T15:59:31.017-0300] {task_command.py:376} INFO - Running <TaskInstance: get_all_nfe_supply.get_endpoint_all_notas scheduled__2022-11-05T00:00:00+00:00 [running]> on host debian
[2022-11-06T15:59:31.832-0300] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_all_nfe_supply
AIRFLOW_CTX_TASK_ID=get_endpoint_all_notas
AIRFLOW_CTX_EXECUTION_DATE=2022-11-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-05T00:00:00+00:00
[2022-11-06T15:59:31.835-0300] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/debian/etlhausz/airflow/dags/get_endpoint.py", line 27, in get_endpoint_all_notas
    return requests.get(API).json()
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant http://None?
[2022-11-06T15:59:32.010-0300] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=get_all_nfe_supply, task_id=get_endpoint_all_notas, execution_date=20221105T000000, start_date=20221106T185930, end_date=20221106T185932
[2022-11-06T15:59:32.042-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 385 for task get_endpoint_all_notas (Invalid URL 'None': No scheme supplied. Perhaps you meant http://None?; 2765)
[2022-11-06T15:59:32.082-0300] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-06T15:59:32.138-0300] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
