[2022-11-06T19:24:41.548-0300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Dag_ETL.task_deca scheduled__2022-11-05T00:00:00+00:00 [queued]>
[2022-11-06T19:24:41.592-0300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Dag_ETL.task_deca scheduled__2022-11-05T00:00:00+00:00 [queued]>
[2022-11-06T19:24:41.592-0300] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-06T19:24:41.594-0300] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-06T19:24:41.594-0300] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-06T19:24:41.641-0300] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): task_deca> on 2022-11-05 00:00:00+00:00
[2022-11-06T19:24:41.656-0300] {standard_task_runner.py:55} INFO - Started process 3452 to run task
[2022-11-06T19:24:41.676-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'Dag_ETL', 'task_deca', 'scheduled__2022-11-05T00:00:00+00:00', '--job-id', '499', '--raw', '--subdir', 'DAGS_FOLDER/teste_excom.py', '--cfg-path', '/tmp/tmpjd1wx8ak']
[2022-11-06T19:24:41.695-0300] {standard_task_runner.py:83} INFO - Job 499: Subtask task_deca
[2022-11-06T19:24:42.040-0300] {task_command.py:376} INFO - Running <TaskInstance: Dag_ETL.task_deca scheduled__2022-11-05T00:00:00+00:00 [running]> on host debian
[2022-11-06T19:24:42.242-0300] {abstractoperator.py:417} ERROR - Exception rendering Jinja template for task 'task_deca', field 'op_kwargs'. Template: {'filename': '{{ var.value.my_dag_filename }}', 'path': '{{ var.value.my_dag_path }}'}
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 410, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 487, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 487, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 474, in render_template
    return render_template_to_string(template, context)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/utils/context.py", line 102, in __getattr__
    self.var = Variable.get(key, deserialize_json=self._deserialize_json)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable my_dag_filename does not exist'
[2022-11-06T19:24:42.254-0300] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1457, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1576, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2199, in render_templates
    original_task.render_template_fields(context)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1193, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 410, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 487, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 487, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 474, in render_template
    return render_template_to_string(template, context)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/utils/context.py", line 102, in __getattr__
    self.var = Variable.get(key, deserialize_json=self._deserialize_json)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable my_dag_filename does not exist'
[2022-11-06T19:24:42.308-0300] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=Dag_ETL, task_id=task_deca, execution_date=20221105T000000, start_date=20221106T222441, end_date=20221106T222442
[2022-11-06T19:24:42.350-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 499 for task task_deca ('Variable my_dag_filename does not exist'; 3452)
[2022-11-06T19:24:42.386-0300] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-06T19:24:42.513-0300] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-06T19:32:11.346-0300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Dag_ETL.task_deca scheduled__2022-11-05T00:00:00+00:00 [queued]>
[2022-11-06T19:32:11.359-0300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Dag_ETL.task_deca scheduled__2022-11-05T00:00:00+00:00 [queued]>
[2022-11-06T19:32:11.359-0300] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-06T19:32:11.360-0300] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-06T19:32:11.360-0300] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-06T19:32:11.377-0300] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): task_deca> on 2022-11-05 00:00:00+00:00
[2022-11-06T19:32:11.399-0300] {standard_task_runner.py:55} INFO - Started process 10821 to run task
[2022-11-06T19:32:11.425-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'Dag_ETL', 'task_deca', 'scheduled__2022-11-05T00:00:00+00:00', '--job-id', '503', '--raw', '--subdir', 'DAGS_FOLDER/teste_excom.py', '--cfg-path', '/tmp/tmpsus1mcsi']
[2022-11-06T19:32:11.426-0300] {standard_task_runner.py:83} INFO - Job 503: Subtask task_deca
[2022-11-06T19:32:11.563-0300] {task_command.py:376} INFO - Running <TaskInstance: Dag_ETL.task_deca scheduled__2022-11-05T00:00:00+00:00 [running]> on host debian
[2022-11-06T19:32:11.634-0300] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Dag_ETL
AIRFLOW_CTX_TASK_ID=task_deca
AIRFLOW_CTX_EXECUTION_DATE=2022-11-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-05T00:00:00+00:00
[2022-11-06T19:32:11.634-0300] {logging_mixin.py:120} INFO - teste
[2022-11-06T19:32:11.635-0300] {python.py:177} INFO - Done. Returned value was: None
[2022-11-06T19:32:11.648-0300] {taskinstance.py:1401} INFO - Marking task as SUCCESS. dag_id=Dag_ETL, task_id=task_deca, execution_date=20221105T000000, start_date=20221106T223211, end_date=20221106T223211
[2022-11-06T19:32:11.697-0300] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-11-06T19:32:11.718-0300] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
