[2022-11-06T17:41:32.619-0300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: get_urls_deca.get_produtos manual__2022-11-06T20:41:18.903442+00:00 [queued]>
[2022-11-06T17:41:32.638-0300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: get_urls_deca.get_produtos manual__2022-11-06T20:41:18.903442+00:00 [queued]>
[2022-11-06T17:41:32.639-0300] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-06T17:41:32.639-0300] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-06T17:41:32.639-0300] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-06T17:41:32.676-0300] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): get_produtos> on 2022-11-06 20:41:18.903442+00:00
[2022-11-06T17:41:32.682-0300] {standard_task_runner.py:55} INFO - Started process 10424 to run task
[2022-11-06T17:41:32.685-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'get_urls_deca', 'get_produtos', 'manual__2022-11-06T20:41:18.903442+00:00', '--job-id', '428', '--raw', '--subdir', 'DAGS_FOLDER/teste_excom.py', '--cfg-path', '/tmp/tmpdgeijugu']
[2022-11-06T17:41:32.685-0300] {standard_task_runner.py:83} INFO - Job 428: Subtask get_produtos
[2022-11-06T17:41:32.826-0300] {task_command.py:376} INFO - Running <TaskInstance: get_urls_deca.get_produtos manual__2022-11-06T20:41:18.903442+00:00 [running]> on host debian
[2022-11-06T17:41:32.908-0300] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_urls_deca
AIRFLOW_CTX_TASK_ID=get_produtos
AIRFLOW_CTX_EXECUTION_DATE=2022-11-06T20:41:18.903442+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-06T20:41:18.903442+00:00
[2022-11-06T17:41:32.956-0300] {logging_mixin.py:120} WARNING - /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/utils/context.py:297 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-11-06T17:41:32.959-0300] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/debian/etlhausz/airflow/dags/teste_excom.py", line 60, in _storing_models
    driver.get(ml_ids)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 441, in get
    self.execute(Command.GET, {'url': url})
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 427, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/selenium/webdriver/remote/remote_connection.py", line 342, in execute
    data = utils.dump_json(params)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/selenium/webdriver/remote/utils.py", line 23, in dump_json
    return json.dumps(json_struct)
  File "/usr/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Query is not JSON serializable
[2022-11-06T17:41:33.017-0300] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=get_urls_deca, task_id=get_produtos, execution_date=20221106T204118, start_date=20221106T204132, end_date=20221106T204133
[2022-11-06T17:41:33.101-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 428 for task get_produtos (Object of type Query is not JSON serializable; 10424)
[2022-11-06T17:41:33.169-0300] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-06T17:41:33.221-0300] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
