[2022-11-06T19:07:38.338-0300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.task_a scheduled__2022-11-05T00:00:00+00:00 [queued]>
[2022-11-06T19:07:38.359-0300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: my_dag.task_a scheduled__2022-11-05T00:00:00+00:00 [queued]>
[2022-11-06T19:07:38.360-0300] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-06T19:07:38.360-0300] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-06T19:07:38.361-0300] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-06T19:07:38.419-0300] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): task_a> on 2022-11-05 00:00:00+00:00
[2022-11-06T19:07:38.435-0300] {standard_task_runner.py:55} INFO - Started process 5020 to run task
[2022-11-06T19:07:38.448-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'my_dag', 'task_a', 'scheduled__2022-11-05T00:00:00+00:00', '--job-id', '495', '--raw', '--subdir', 'DAGS_FOLDER/teste_excom.py', '--cfg-path', '/tmp/tmpi9qgfikr']
[2022-11-06T19:07:38.449-0300] {standard_task_runner.py:83} INFO - Job 495: Subtask task_a
[2022-11-06T19:07:38.635-0300] {task_command.py:376} INFO - Running <TaskInstance: my_dag.task_a scheduled__2022-11-05T00:00:00+00:00 [running]> on host debian
[2022-11-06T19:07:38.719-0300] {abstractoperator.py:417} ERROR - Exception rendering Jinja template for task 'task_a', field 'op_kwargs'. Template: {'filename': '{{ var.value.my_dag_filename }}', 'path': '{{ var.value.my_dag_path }}'}
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 410, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 487, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 487, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 474, in render_template
    return render_template_to_string(template, context)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/utils/context.py", line 102, in __getattr__
    self.var = Variable.get(key, deserialize_json=self._deserialize_json)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable my_dag_filename does not exist'
[2022-11-06T19:07:38.726-0300] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1457, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1576, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2199, in render_templates
    original_task.render_template_fields(context)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1193, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 410, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 487, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 487, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 474, in render_template
    return render_template_to_string(template, context)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/utils/context.py", line 102, in __getattr__
    self.var = Variable.get(key, deserialize_json=self._deserialize_json)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable my_dag_filename does not exist'
[2022-11-06T19:07:38.758-0300] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=my_dag, task_id=task_a, execution_date=20221105T000000, start_date=20221106T220738, end_date=20221106T220738
[2022-11-06T19:07:38.788-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 495 for task task_a ('Variable my_dag_filename does not exist'; 5020)
[2022-11-06T19:07:38.821-0300] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-06T19:07:38.857-0300] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
